# on webservers we install apache, passenger, ruby and other Canvas dependencies

# Update software on server first
  - name: Update Packets
    apt:
      name: "*"
      state: latest

# Add Ruby Repo
  - name: Install gnupg
    apt:
      name: "gnupg"
      state: latest
  - name: Add Ruby repo
    apt_repository:
      repo: ppa:instructure/ruby
      update_cache: yes

# Add Passenger Repo
  - name: Install dirmngr
    apt:
      name: "dirmngr,curl"
      state: latest
  - name: Add an apt key
    apt_key:
        keyserver: keyserver.ubuntu.com
        id: 561F9B9CAC40B2F7
  - name: Install apt-transport-https ca-certificates
    apt:
      name: "apt-transport-https,ca-certificates"
      state: latest
  - name: Install passenger gpg-key
    shell: sh -c 'curl https://oss-binaries.phusionpassenger.com/auto-software-signing-gpg-key.txt | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/phusion.gpg >/dev/null'
    args:
      creates: /etc/apt/trusted.gpg.d/phusion.gpg
  - name: Adding passenger repo
    shell: sh -c 'echo deb https://oss-binaries.phusionpassenger.com/apt/passenger jammy main > /etc/apt/sources.list.d/passenger.list'
    args:
       creates: /etc/apt/sources.list.d/passenger.list

# Install CanvasLMS dependencies
  - name: Install CanvasLMS dependencies
    apt:
      name: "ruby3.3,ruby3.3-dev,zlib1g-dev,libxml2-dev,libsqlite3-dev,libpq-dev,libxmlsec1-dev,libyaml-dev,libidn11-dev,make,g++"
      state: present  
      update_cache: yes

# Install Node.js
  - name: Download and import the Nodesource GPG key
    shell: sh -c 'curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg'
    args:
      creates: /etc/apt/keyrings/nodesource.gpg

  - name: Node.js installation - Create deb repository
    shell: sh -c 'echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list'
    args:
       creates: /etc/apt/sources.list.d/nodesource.list

  - name: Install Nodejs 22 via apt
    apt:
      name: "nodejs"
      state: latest
      update_cache: yes

  - name: Install NPM
    shell: sh -c 'sudo npm install -g npm@latest'

# Install Yarn
  - name: Remove Yarn if already installed
    apt:
      name: yarn
      state: absent

  - name: Install Yarn
    shell: npm -g install yarn
    
# Install Bundler
  - name: Install Bundler
    shell: gem install bundler

# By default we run postfix SMTP server on web node
  - name: Install Postfix SMTP Server
    apt:
     name: postfix
     state: latest
  - name: Fix smtpd for Canvas
    replace:
      path: /etc/postfix/main.cf
      regexp: 'smtpd_use_tls=yes'
      replace: 'smtpd_use_tls=no'
  - name: Restart postfix
    service:
       name: postfix
       state: restarted
       enabled: yes

# Install and Configure Apache web server
  - name: Install Apache Web server
    apt:
      name: "passenger,libapache2-mod-passenger,apache2,libapache2-mod-xsendfile"
      state: present  
      update_cache: yes

  - name: Install certbot
    apt:
      name: "certbot,python3-certbot-apache"
      state: latest

# Enable module rewrite
  - apache2_module:
      state: present
      name: "rewrite"
  - apache2_module:
      state: present
      name: "passenger"
  - apache2_module:
      state: present
      name: "ssl"
# remove default vhost
  - name: Remove 000-default.conf apache Vhost
    file:
      path: /etc/apache2/sites-enabled/000-default.conf
      state: absent
# create Apache config for Canvas
  - name: Create Apache config for Canvas
    template:
        src: templates/apache-vhost.conf.j2
        dest: "/etc/apache2/sites-enabled/{{ domain_name }}.conf"
        owner: root
        group: root
        mode: '0644'
  - name: Tune Passenger
    template:
        src: templates/passenger.conf.j2
        dest: "/etc/apache2/mods-enabled/passenger.conf"
        owner: root
        group: root
        mode: '0644'
